WITH upstream_modems AS (
  SELECT
    csudf.CMTS_ID,
    csudf.CABLE_MAC,
    ucc.SG_ID,
    COUNT(DISTINCT csudf.CM_MAC) AS US_CM_COUNT,
    COUNT(DISTINCT CASE WHEN ca.BASE_CAPABILITY = 'docsis20' THEN csudf.CM_MAC END) AS DOCSIS20_CM_COUNT,
    COUNT(DISTINCT CASE WHEN ca.BASE_CAPABILITY = 'docsis30' THEN csudf.CM_MAC END) AS DOCSIS30_CM_COUNT,
    COUNT(DISTINCT CASE WHEN ca.BASE_CAPABILITY = 'docsis31' THEN csudf.CM_MAC END) AS DOCSIS31_CM_COUNT
  FROM cabletica.CM_SCQ_UP_DAY_FACTS csudf
  JOIN cabletica.UP_CHANNEL_CONFIG ucc
    ON csudf.CMTS_ID = ucc.CMTS_ID
   AND csudf.CHANNEL_NAME = ucc.CHANNEL_NAME
  LEFT JOIN cabletica.CM_ATTRIBUTES ca
    ON csudf.CM_MAC = ca.MACADDR
  WHERE csudf.PTIME = (SELECT MAX(PTIME) FROM cabletica.CM_SCQ_UP_DAY_FACTS)
    AND csudf.CABLE_MAC != ''
  GROUP BY csudf.CMTS_ID, csudf.CABLE_MAC, ucc.SG_ID
),
sg_sizes AS (
  SELECT
    CMTS_ID,
    CABLE_MAC,
    COUNT(DISTINCT SG_ID) AS SG_SIZE
  FROM cabletica.UP_CHANNEL_CONFIG
  GROUP BY CMTS_ID, CABLE_MAC
)
SELECT
  u.CMTS_ID,
  u.CABLE_MAC,
  u.SG_ID,
  u.US_CM_COUNT,
  u.DOCSIS20_CM_COUNT,
  u.DOCSIS30_CM_COUNT,
  u.DOCSIS31_CM_COUNT,
  s.SG_SIZE
FROM upstream_modems u
LEFT JOIN sg_sizes s ON u.CMTS_ID = s.CMTS_ID AND u.CABLE_MAC = s.CABLE_MAC;
