SELECT
    CMTS_ID,
    CABLE_MAC,
    AVG(MAX_PROFILE_MAX_BW_DOWN) AS DS_AVG_PROFILE,
    AVG(MAX_PROFILE_MAX_BW_UP) AS US_AVG_PROFILE,
    COUNT(*) AS CM_COUNT
FROM (
    SELECT
        CMTS_ID,
        CABLE_MAC,
        MAX(PROFILE_MAX_BW_DOWN) AS MAX_PROFILE_MAX_BW_DOWN,
        MAX(PROFILE_MAX_BW_UP) AS MAX_PROFILE_MAX_BW_UP
    FROM cabletica.CM_DATA_DAY_FACTS
    WHERE PTIME = (SELECT MAX(PTIME) FROM cabletica.CM_DATA_DAY_FACTS)
    GROUP BY CMTS_ID, CABLE_MAC, CM_MAC
) AS per_mac_max
GROUP BY CMTS_ID, CABLE_MAC;
