SELECT CMTS_ID, CHANNEL_NAME AS REF_CHAN, FIBER_NODE
FROM cabletica.CHANNEL_TO_PHY_FIBER_NODE
WHERE DIRECTION = 'UP'
AND LAST_UPDATE_TIME = (SELECT MAX(LAST_UPDATE_TIME) FROM CHANNEL_TO_PHY_FIBER_NODE);
