SELECT
    CMTS_ID,
    CABLE_MAC,
    CHANNEL_NAME,
    MAX(MS_UTILIZATION) AS MS_UTILIZATION
FROM
    UP_UTIL_FACTS
WHERE
    PTIME BETWEEN '{{start_date}}' AND '{{end_date}}'
GROUP BY
    CMTS_ID, CABLE_MAC, CHANNEL_NAME;
